
development:
  adapter: postgresql
  database: hangerz_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: hangerz_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: hangerz
  pool: 5
  timeout: 5000
